### ISSUE TITLE
Permissions issue for App Registration

### ISSUE THREAD

**Issue by hazcod** [nv-pipo/misp-to-sentinel-and-defender-connector#3]
Hi,

Thank you for your work!
I've forked and refactored your code a bit, but I keep running into a permissions issue when querying in `__get_misp_ids_of_recent_ioc_in_sentinel`.
I've assigned the right API roles to the app registration and have given consent, but it still reports:

```
Exception: https://management.azure.com/subscriptions/XXX/resourceGroups/siem/providers/Microsoft.OperationalInsights/workspaces/sentinelsiem/providers/Microsoft.SecurityInsights/threatIntelligence/main/queryIndicators?api-version=2022-07-01-preview -> The client 'YYY' with object id '566dc768-206f-4ba0-a3d2-XXX' does not have authorization to perform action 'microsoft.SecurityInsights/threatIntelligence/queryIndicators/read' over scope '/subscriptions/XXX/resourceGroups/siem/providers/Microsoft.OperationalInsights/workspaces/sentinelsiem/providers/Microsoft.SecurityInsights/threatIntelligence/main' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

Do you recall needing to do anything special about that? Thanks.

**Comment by hazcod** [comment]
I was also wondering the use of `https://management.azure.com/` as the API base URL when we need to add permissions using for the Graph API, which lives at `graph.microsoft.com`?

**Comment by nv-pipo** [comment]
Hi,
I changed some code 25 days ago and still haven't updated the documentation.
Indeed, `graph.microsoft.com` permissions are no longer required. In contrast, `management.azure.com` does not rely on API permissions, but RBAC permissions to the resource. You can create a role with the following permissions:
```json
"permissions": [
    {
        "actions": [
            "Microsoft.SecurityInsights/threatIntelligence/queryIndicators/*",
            "Microsoft.SecurityInsights/threatIntelligence/createIndicator/*"
        ],
        "notActions": [],
        "dataActions": [],
        "notDataActions": []
    }
]
```
Then assign the SP to have that Role for the resource group that contains Sentinel.

Hope it's clear enough.
